sudo: false

language: erlang

branches:
  only:
  - master
  - /^\d+\..*/ # version tags

# Two stages, so that basic tests are run first
stages:
  - basic
  - test

matrix:
  fast_finish: true

  # Jobs that are allowed to fail:
  allow_failures:
  - env: TEST=".travis/travis_has_latest_otp_version"
  - env: TEST="make -C docs test-external"
  - env: TEST="make -C doc test-external"

  include:

  # When otp_release is unspecified, the first value in the corresponding
  # list further down in this file will be used

  # Check that the latest Erlang version is tested
  # See the warning printed by the script to understand why this test
  # has a separate otp_release specification.
  - env: TEST=".travis/travis_has_latest_otp_version"
    otp_release: 21.1
    stage: basic

  # Check dialyzer
  - env: TEST="make dialyzer"
    stage: basic

  # Check lint
  - env: TEST="make lint"
    stage: basic

  # Test documentation
  - env: TEST="make -C doc test"
    stage: basic

  # Minimal support for R16B03-1
  - env: TEST="make tests-real"
    otp_release: R16B03-1
    stage: test

  # Test website
  - env: TEST="make -C docs test"
    stage: test

  # Test external links separately, cause they can break unexpectedly
  - env: TEST="make -C docs test-external"
    stage: test
    addons:
      apt:
        packages:
        - libcurl4-openssl-dev # required to avoid SSL errors in htmlproofer

env:

  # FLAG is used by Codecov reporter (.travis/after_success)
  - TEST=".travis/maybe_cover make tests" FLAG="tests"
  - TEST=".travis/maybe_cover make tests-real" FLAG="tests_real"
  - TEST="make tests-unit" FLAG="unit_tests"

otp_release:

  # Two latest minor versions of the most recent OTP release.

  # When a new major OTP release is enabled, also update the badge in
  # README.md and the argument given to generate_version_hrl in
  # rebar.config

  - 21.1
  - 21.0

  # Last minor version of older OTP releases

  - 20.3
  - 19.3
  - 18.3
  - 17.5
  # R16B03-1 is minimally supported (see matrix section)


# Travis build steps configuration

cache:
  directories:
  - "$HOME/.cache/rebar3"

before_script:
  - .travis/before_script

script:
 - $TEST

after_success:
  - .travis/after_success

after_failure:
  - .travis/after_failure
