# Base config
title: "Concuerror"
description: "Concuerror is a model checking tool for debugging, testing and verifying concurrent Erlang programs."
logo: "/images/site-logo.png"
url: "https://concuerror.com"

# Owner/author information
author: stavros

# Analytics and webmaster tools stuff goes here
google_analytics: "G-PJT79WHMGH"

# Theme
remote_theme: "aronisstav/so-simple-theme"
skin: "/assets/css/skins/default.css"
locale: en-US
date_format: "%B %-d, %Y"

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

read_time: true
words_per_minute: 50

# Search
search_full_content: true

# Taxonomy pages
category_archive_path: /

# Fonts
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Footer Links
footer_links:
  - title: Home
    url: /
    icon: fas fa-home
  - title: Github
    url: https://github.com/parapluu/Concuerror
    icon: fab fa-github
  - title: Github Stars
    url: https://github.com/parapluu/Concuerror/stargazers
    icon: fas fa-star
  - title: Feed
    url: feed.xml
    icon: fas fa-rss-square

# Liquid
liquid:
  error_mode: strict

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title:output_ext

# Markdown
markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  syntax_highlighter: rouge
  toc_levels: 1..6

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag

# Feed
feed:
  path: "feed.xml"

# Redirects
redirect_from:
  json: false

# Include/exclude
include: [".htaccess"]
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "Makefile", "README.md", "vendor"]

